# Generated by Django 4.1 on 2022-09-18 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date_reminder', models.DateField()),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('date_message', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_reminder', to='reminder.reminder')),
            ],
        ),
    ]
