# Generated by Django 4.1 on 2022-09-19 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_reminder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_reminder', to='reminder.reminder'),
        ),
    ]
